### ISSUE TITLE
Include the documentation on the website on right hand side

### ISSUE THREAD

**Issue by phamductri** [allenhwkim/angularjs-google-maps#163]
include the content in this link : https://rawgit.com/allenhwkim/angularjs-google-maps/master/build/docs/index.html on the right hand side of the website http://ngmap.github.io/, before all the examples. Right now it's included in the index page, but seeing the examples on one site but the docs on another site make the reading is rather difficult.

**Comment by allenhwkim** [comment]
ngMap.github.io is mobile friendly, but documentation is not.
So if we move the navigation to the left, and  you see documentation in mobile browser, you will see the menu only.
This was intentional and it needs to be improved as a mobile friendly version. Simply moving the navigation is not a good solution, i think.

**Comment by allenhwkim** [comment]
Closing
