### ISSUE TITLE
Error: [$rootScope:inprog] $digest already in progress, When adding on-center-changed event 

### ISSUE THREAD

**Issue by elennaro** [allenhwkim/angularjs-google-maps#181]
Hello.
I've made a jsfiddle to reproduce this bug:
http://jsfiddle.net/elennaro/94pdbo92/

**Comment by allenhwkim** [comment]
This happens because when you use asynchronous geo lookup to find your current location, map is initialized but there is no center found.

There is a callback for it, `geo-callback`, this is only called when geo-lookup is successful.

http://plnkr.co/edit/7Of0vCaOkVB8pMCXRNcj?p=preview

Actually you do not need to have a callback to position marker for your current location. You can simply set location as `current-location`

**Comment by elennaro** [comment]
Thanks for the answer @allenhwkim, and for the awesome library too.
I need callback to position marker because I want it to stay in center when user drags the map.

So I [figured out](http://jsfiddle.net/elennaro/94pdbo92/1/) that the error happens [here on this apply call](https://github.com/allenhwkim/angularjs-google-maps/blob/master/app/scripts/services/attr2_options.js#L204)

Cannot yet debug it normally :( What calls this **[eventFunc](https://github.com/allenhwkim/angularjs-google-maps/blob/master/app/scripts/services/attr2_options.js#L194)** and what for?

**Comment by allenhwkim** [comment]
I know the problem, but I did not think it was serious.
It was caused by two $apply() one by geo coding, and the other by center-changed event. 

We can simply fix this by changing $apply to $timeout.

http://plnkr.co/edit/3e5ZIocsu4JUSZvDjREa?p=preview

this plnkr works, but I need to run some test with it. Please be patient.

**Comment by elennaro** [comment]
Thanks @allenhwkim. I usually do `$timeout(f(){/* change scope */; $scope.$digest;},$scope.$$phase ? 5 : 0);` Wherever I'm not sure that digest progresses will overlap in time.

**Comment by allenhwkim** [comment]
This fix is released with version 1.7.7. Please reopen this issue if the problem is persistent

**Comment by elennaro** [comment]
Thank you!

**Comment by allenhwkim** [comment]
repatched with version 1.7.9
