### ISSUE TITLE
How to show all the info windows simultaneously on the placed markers when they appear, not on click.!

### ISSUE THREAD

**Issue by angelobsks** [allenhwkim/angularjs-google-maps#203]
Let's say we have a map, an info window defined and a number of marker placed on the map with ng-repeat.
How can i show for each marker its info-window opened when the marker appears ? 
Not on the click event. 
I have already do it on click and it works fine.

![image](https://cloud.githubusercontent.com/assets/12217433/7567902/6ae2cdbc-f808-11e4-90ae-6496cf5aa4bc.png)

Something like that below ...
![image](https://cloud.githubusercontent.com/assets/12217433/7568062/466671f4-f809-11e4-8c3a-e4da1c1b7fae.png)

**Comment by allenhwkim** [comment]
You cannot do that with only one infowindow. When clicked other marker, the infoWindow simply re-compile and moves its position. it's not multiple infoWindow because you defined it as only one.

You need to create multiple infoWindow to open multiple infoWindow at the same time.

Please checkout this example,
https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/infowindow_compile.html

and also this example that uses `visible-on-marker` attribute.
https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/infowindow-simple.html

For more examples, please visit index page
https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/index.html

**Comment by allenhwkim** [comment]
Closing
