### ISSUE TITLE
Listening to zoom and drag events

### ISSUE THREAD

**Issue by markolbert** [allenhwkim/angularjs-google-maps#209]
I'm a little confused as to how to listen to zoom and drag events. Do I setup an angular listener (e.g., $scope.$on("dragend", function()...)) or do I reference in the map markup and define a method?

In looking at the examples I noticed that the second approach -- putting the on... attribute in the markup -- is what's used. But I also noticed that the handler method was defined within the map initialized event handler (which uses the listener approach). Does the handler have to be defined within the map initialized callback?

**Comment by allenhwkim** [comment]
As you see here, 
https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/events.html

Events are assigned as an attribute with prefix of `on-`. You can use `on-dragend` since it is a google map event(https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/map_events.html)

Please code like this, `on-dragend=myFunctionInScope`

For more examples, https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/index.html

**Comment by markolbert** [comment]
Thanx, Allen!

**Comment by markolbert** [comment]
Allen,

I'm running into an issue where changing the icon used to represent a marker on the map is not being updated (i.e., the icon gets changed in code, but the new marker doesn't get displayed).

I didn't want to open an issue on this because I'm not sure if it's my ignorance of angularjs, a problem with angular, or something in ng-map.

I put a plunker together to demonstrate the issue. It's described in an SO question you can find at http://stackoverflow.com/questions/30249110/angularjs-force-ng-repeat-update-when-property-of-an-element-changes


-          Mark
