### ISSUE TITLE
Wrong InfoWindow position when opening outside the map

### ISSUE THREAD

**Issue by kaiga747** [allenhwkim/angularjs-google-maps#223]
Hello,

A have a little problem with opening InfoWindow on marker position outside the map. Thing is - i'm using MarkerClusterer, but still i've wanted to check it with you guys here.

Here's my app:
http://plnkr.co/edit/NjjHYBBlyJVxuQFHuKiA?p=preview

The problem is - InfoWindow opens just fine right on the marker if you click the marker itself, but if i select a position from the list below and the marker of position selected is in cluster the InfoWindow will not get the position. The strange thing is, i've inspected it and the InfoWindow object have an anchor which contains correct position, so after couple of hours with it i just run out of ideas where to look.

I've also checked if markers "visible" change if they are in the cluster but that's not changing by state at all.

**Comment by allenhwkim** [comment]
The underlying problem for this approach is marker visibility, which is controlled by MarkerClusterer.

That's why when you click marker, and InfoWindow shows fine, but with your programming, which skips the steps of showing marker by MarkerClusterer, it shows the position, but without marker.

The best approach what I think of is;
0. make it sure marker is added with MarkerClusterer.
1. show marker by using MarkerClusterer
2. click marker by program.

I cannot dig into MarkerClusterer now, but you may try.
