### ISSUE TITLE
Markers not reloading on subsequent view load

### ISSUE THREAD

**Issue by PBartrina** [allenhwkim/angularjs-google-maps#400]
Markers do not attach correctly to the map once the view in which the map is is reloaded (route to different view, and then route back to the map's view).

I am doing it as follows:

```javascript
NgMap.getMap().then(function (map) {
    var marker = new google.maps.Marker({ position: new google.maps.LatLng(lat, long),
                           map: map,
                           title: 'marker',
                           icon: 'route/to/icon.png'
    });
}
```

The first execution, with a fresh controller, works perfect. But when going away and back to this view, the markers don't show. When logging the __marker__ variable the output shows map attribute as a *null* value.

**Comment by allenhwkim** [comment]
I do not understand why you add marker with Javascript. There is a lot easier way to add marker with HTML than Javascript.

I think you are adding marker only once by your program. When you comeback from other route, your map will be re-created by your view, but you are not adding marker every single time.

I recommend to use HTML instead of Javascript to add marker to your map. Examples are here.

http://ngmap.github.io/#/marker-simple.html
http://ngmap.github.io/#/marker.html
http://ngmap.github.io/#/marker_dynamic_ng_repeat.html
http://ngmap.github.io/#/marker_data_with_ng_repeat.html

**Comment by PBartrina** [comment]
I simplified the example showing the exact part which isn't working. I have a bridge to cordova in which I receive location and InfoWindow data asynchronously. It actually loads quite a load of markers and I wanted to avoid the ng-repeat because of its cost in the digest cycle, even though the HTML solution worked correctly.

I'll make a plunker showing the issue as soon as I can to show the issue.

**Comment by allenhwkim** [comment]
"quite a load of markers " can be avoided by using filter as you know already.
If that's not the case, there is `no-watcher` option to avoid observers for your markers. I have tested with 1000 markers with `no-watcher="true"`, and it worked fine.

BTW, I have tested with ui-router solution, and it worked fine. https://ngmap.github.io/#/ui-router.html
If you can reproduce your issue with plunker, I will reopen this issue. Till then, remaining closed.
