### ISSUE TITLE
The ng-map is not loaded on the popup after the second click

### ISSUE THREAD

**Issue by cesarcastmore** [allenhwkim/angularjs-google-maps#500]
I have been developing a popup using ngMap and UIBoostrap but after the second click the map is not loaded. Could you help to solve my mistake?

http://plnkr.co/edit/9qL26v92mtpo7HaV3AqH

**Comment by allenhwkim** [comment]
This happens when second click happens, map width/height is 0px and 0px, and it's not redrawn with the full size of div, which is unlike the first load.

You need to redraw the map for this case.
http://plnkr.co/edit/Q0wfO9zNecaQQcuvpxCN?p=preview

Hope there is easier solution for this kind of case.
