### ISSUE TITLE
custom markers are not draggable

### ISSUE THREAD

**Issue by prusswan** [allenhwkim/angularjs-google-maps#531]
Is this intended? There is no example with both `custom-marker` and `draggable` and I could not get it to work either

**Comment by allenhwkim** [comment]
custom marker is not draggable because it does not inherit the property of markers, but a custom overlay.

To make it draggable, we need to implement event listeners of mousedown, mousemove, and mouse up.

Example, http://stackoverflow.com/questions/22127626/can-we-make-custom-overlays-draggable-on-google-maps-v3


If this feature is required by many, it would be worth spending time for it.

**Comment by prusswan** [comment]
I see. I wanted to avoid the use of MarkerWithLabel, but I will try something else then.

**Comment by idrenski** [comment]
I also would like to have custom markers draggable. More people work with custom markers and they should be fully functional.
