### ISSUE TITLE
info-window doesn't work with ng-repeat?

### ISSUE THREAD

**Issue by jough** [allenhwkim/angularjs-google-maps#56]
I can't seem to make the info window display if the markers are created with ng-repeat. Is this a scope issue?

Plunkr example: http://plnkr.co/edit/otK2L5ktviQ06qusx1nC?p=preview

**Comment by lucasroselli** [comment]
All plunkers examples here are not working , so I wrote my on solution:
http://plnkr.co/edit/eEE9tX4PlDstCeiQI6x2?p=preview

I create the info window on a click event, then I have full control of the info window

**Comment by allenhwkim** [comment]
If the old plunker does not work, please check these out

https://github.com/allenhwkim/angularjs-google-maps/blob/master/testapp/marker_with_ng_repeat.html
https://rawgit.com/allenhwkim/angularjs-google-maps/master/testapp/marker_with_ng_repeat.html

**Comment by lucasroselli** [comment]
Hi Allen Kim,

Thanks for your response, but the marker is not a problem for me, but the
info window inside a ng-repeat doesn't work with a scope, even removing the
ng-non-bindble from the info.

That's why I created the info on a controller.

2015-02-10 14:07 GMT-02:00 Allen Kim <notifications@github.com>:

**Comment by renilbabu03** [comment]
@lucasroselli Thanks....It worked for me...

**Comment by sagarmaharjan** [comment]
@lucasroselli It work for me but infowindow cover the marker. how to fix this problem????

**Comment by allenhwkim** [comment]
Please follow this example

https://ngmap.github.io/#/!infowindow_ng_click.html
