### ISSUE TITLE
draggable="true" map option vs Safari

### ISSUE THREAD

**Issue by flc** [allenhwkim/angularjs-google-maps#589]
http://plnkr.co/edit/eyHa5LKLdgRhOGZzcNKb?p=preview
Start dragging the map in Safari. I tested it in Safari for Windows but produces similarly weird behavior on osx as well.
If draggable="true" is removed dragging is ok.

https://jsfiddle.net/qo5sqg9u/2/
This is a simple map without ng-map. Dragging looks ok in Safari.

I can only encounter this weird behavior using the Safari browser.

**Comment by allenhwkim** [comment]
I think safari is using an experimental techonology, https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/draggable, and confusing the map.

Techncally, `<ng-map>` is not a visible element, so this `draggable` attribute should not affect any. However when draggable is defined in the container, it may result in differently.

We can come up with a solution to change draggable attribute to something else after the map is initialized, so that the element will not have `draggable` attribute any more, which confuses Safari browser.

**Comment by flc** [comment]
or one can just use `data-draggable="true"` ...
nice finding, Kim, thx!

btw it's not really an issue since the fix of https://github.com/allenhwkim/angularjs-google-maps/issues/540 because `true` is the default for `draggable` so one can just not specify it + `draggable="false"` doesn't seem to cause any harm.

however a mention in the doc or somewhere could be useful probably. what do you think?

**Comment by allenhwkim** [comment]
I try to make all Google API map options as it is in the attribute. e.g zoom option is zoom attribue, center is center attribute.

So, draggable should be draggable attribute. Internally we can change it to `data-draggable` attribute, so the browser does not read it as element draggable.

**Comment by flc** [comment]
I mean, right now. If I use `data-draggable` instead of `draggable` (or any `data-*`) it works just fine as well. Shouldn't it? :)

**Comment by allenhwkim** [comment]
@flc, yes it works only if the data is not dynamic. `data-draggable="{{draggable}}"` will not work because it won't do any to map.
