### ISSUE TITLE
When loading via webpack, console message "WARNING: Tried to load angular more than once" is shown.

### ISSUE THREAD

**Issue by BrentWheeldon** [allenhwkim/angularjs-google-maps#692]
**Steps to reproduce and a minimal demo(Plunker Example)**

We include ngMap via webpack with code like this:

```
import ngMap from "ngmap";

const myApp = angular.module("myApp", [
  ngMap
]);
```

**Current behavior**

In our karma specs we now get a console message:

`'WARNING: Tried to load angular more than once.'`

**Expected/desired behavior**

No console output.

**Other information**

This seems similar to the comment in https://github.com/allenhwkim/angularjs-google-maps/issues/535, but that issue was closed without information on how to fix this.

**Comment by allenhwkim** [comment]
I don't know how others solve this. All I can say is that `ngMap` should be loaded externally before the main app is loaded, and should not be added twice because of this line.
https://github.com/allenhwkim/angularjs-google-maps/blob/master/build/scripts/ng-map.js#L34

```
angular.module('ngMap', []);
```
Not much skilled with webpack. Sorry, not much helpful. :(
