### ISSUE TITLE
Multiple maps with data layers

### ISSUE THREAD

**Issue by saby-echo** [allenhwkim/angularjs-google-maps#698]
I am trying to use ngMap with <map-data> multiple times in my app. I have marked each <ng-map> with different ids. But it is not working and I think the issue is related to this line:
https://github.com/allenhwkim/angularjs-google-maps/blob/master/directives/map-data.js#L35
NgMap.getMap() is being called with no arguments

**Comment by allenhwkim** [comment]
Have you tried it with `NgMap.getMap(id)`?

**Comment by saby-echo** [comment]
No I didn't modify the library code. I intend to try it as soon as I get time. But I can tell you that <map-data> directive was not working properly. It was failing to get the correct map. In fact as I had no map with id=0, the promise was getting rejected.

**Comment by allenhwkim** [comment]
Do you have any example? For me it works fine. e.g. http://ngmap.github.io/#/!ui-router.html

**Comment by saby-echo** [comment]
The example you gave is not using the data-layer. Give me an hour I will get an example ready for you.

**Comment by saby-echo** [comment]
I combined your given example with http://ngmap.github.io/#/!layer-data-simple.html

https://gist.github.com/saby-echo/81e7ddcd3456c4f0707f86059184b4af

You will see in the original example, the load-geojson attribute works and shows the Google logo over Australia. But in my example when I am providing ids to ngMap like "<ngMap id="foomap">", it stops working.

**Comment by allenhwkim** [comment]
Thanks.. http://plnkr.co/edit/SFjByBN0oRylw0m1iLCZ?p=preview

I will take a look at it later. so busy. 

Any volunteer?

**Comment by TonyWilk** [comment]
Had a quick look at this since I may want to use data on a map eventually... 
The link function in _map-data.js_ can be modified to receive the mapController in the same way as other link functions in ng-map, then pass the id to  NgMap.getMap()
```
      link: function(scope, element, attrs, mapController) {
		mapController = mapController[0]||mapController[1];
		
        var filtered = parser.filter(attrs);
        var options = parser.getOptions(filtered, {scope: scope});
        var events = parser.getEvents(scope, filtered, events);

        console.log('map-data options', options);
        NgMap.getMap(mapController.map.id).then(function(map) {

```
It then works with your "foomap" and "barmap".

However...
this leaves you with another problem: the google data class method _loadGeoJson()_ **_adds_** the features to the map. The result with the example translucent 'Google' is that it gets darker on each page switch as more copies of the data are added to the map.

I would suggest you add a 'geoJson' function to your fooCtrl $scope to get the _map_ and call  _map.data.loadGeoJson("http...   ")_ , you could then do:
`        <ng-map id="foomap" ....    ng-init="geoJson(...)">`

Note that, by default, your controllers are instantiated on page switches as well - so you'll either have to have some flag to make sure you only loadGeoJson() once.
        
Yours,
  TonyWilk

see: [Google Map API - Data class](https://developers.google.com/maps/documentation/javascript/reference#Data)
