### ISSUE TITLE
Odd corrupt map (only one tile) when recreating map 

### ISSUE THREAD

**Issue by TonyWilk** [allenhwkim/angularjs-google-maps#718]
**Steps to reproduce... or not**
I can't exactly define the circumstances. I have an angular app using ui-Router to swop pages, when a page with the <ng-map> is swapped in the map is shown and when it's swapped out NgMap deletes that controller instance. 
This works ok most of the time but in one case changing the page shows a corrupt map. 

**Current behavior**
On navigating back to a page with <ng-map id="mymap" ... > the map only shows a single tile at top left, the rest of the map div is a light grey.

**Other information**
This odd behavior stopped when I replaced center,zoom,tilt and map-type-id attributes in <ng-map> with simple strings. Using e.g. center="{{mycontroller.center}}" caused the problem when switching from a particular page.

Eventually I seem to have fixed this by:

in NgMap.deleteMap(), just before the line:   
```
  delete mapControllers[mapId];
```
I added
```
  NgMapPool.deleteMapInstance(mapId);
```
This requires implementing deleteMapInstance in NgMapPool:
```
  var deleteMapInstance= function(mapId){
	  for( var i=0; i<mapInstances.length; i++ ){
		  if( (mapInstances[i] !== null) && (mapInstances[i].id == mapId)){
			  mapInstances[i]= null;
			  mapInstances.splice( i, 1 );
		  }
	  }
  };

```
and injecting NgMapPool in NgMap.

**Conclusion**
This fix works for me. It may be some odd race condition or some bug in my code causing this to happen - but if you happen to come across this problem, the above may help.

Yours,
  TonyWilk

**Comment by sebrojas14** [comment]
Tony, can you please help me with this?

**Comment by sebrojas14** [comment]
I made a pull request with your code https://github.com/allenhwkim/angularjs-google-maps/pull/729

**Comment by radimhornicek** [comment]
This happend also when you resize a map <div> container  (e.g. with lazy-loading directive within ng-include template), it is important to call     

var map = NgMapPool.mapInstances[0];
google.maps.event.trigger(map, "resize");
map.setCenter(new google.maps.LatLng(your_x_position, your_y_position));

just before a map <div> is loaded (in my case before ng-include template in modal is re-opened because first load works fine). I have a modal (materializecss.com) - so I run code above in modal's onReady callback function placed in my modal directive (don't forget to inject NgMapPool DI in your directive or controller)

It's absolutely not necessarily to rewrite anything in original Angular Google Maps code. I belive this is a matter of Google map plugin itself, so it will work for a lot of another cases with "gray rectangle issues". 

Hope this'll helpful.
