### ISSUE TITLE
Angular maps info window anchor

### ISSUE THREAD

**Issue by lironbar** [allenhwkim/angularjs-google-maps#847]
Is there an option to set the info window anchor position few px above its location?

**Comment by allenhwkim** [comment]
That's google maps setting. 

https://developers.google.com/maps/documentation/javascript/infowindows.
https://developers.google.com/maps/documentation/javascript/3.exp/reference#InfoWindowOptions

 I see `setPosition` and `pixelOffset`. 

People may wonder why I am just referencing google document without the actual implementation. It's because this is just wrapper of google maps api, and the implementation is just exactly the same as google api by setting attribute or using vanilla Javascript.

Closing this as out of scope.
