### ISSUE TITLE
Autocomplete first choice default

### ISSUE THREAD

**Issue by Alarty** [allenhwkim/angularjs-google-maps#856]
When implementing autocomplete input, even in your example (https://ngmap.github.io/#/!places-auto-complete.html) you need to select one of the suggested entries to perform the action.

So if you start typing e.g. "Texa" and hit enter key, nothing happened (or more precisely an error but it's not the point).

A great thing would be to add an option, that take the first suggested entry and typing "Texa" and hit enter would redirect to Texas.

**Comment by allenhwkim** [comment]
Please take a look at this.

https://stackoverflow.com/a/27867610/454252

**Comment by Alarty** [comment]
Great, the first link did the trick.

Don't you think it would be a good add to your library ?

**Comment by allenhwkim** [comment]
> Don't you think it would be a good add to your library ?
No, I don't think so. This module wants to work nothing but as a wrapper of Google Maps. I am trying not to introduce another attribute( or parameter) to users, so that they don't need to learn one more.

![image](https://user-images.githubusercontent.com/1437734/35051909-4ae3dd5e-fb74-11e7-8450-6814482dcce2.png)
